services:
  gateway:
    container_name: bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dLxzopda4a79!
      POSTGRES_DB: gift_hunter
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local